### ISSUE TITLE
Unable to run dev.

### ISSUE THREAD

**Issue by Yager0ne** [sherwyn11/E-Voting-App#20]
Hi Sherwyn,

Thank you so much for the effort and making your project available to everyone.
Would you be so kind to help me on a small issue that I stumbled upon while running the project.
First of all I am not a coder and have little to no knowledge on it.
I am unable to run the "dev" on my test machine, I was able to load the web page but, the "npm run dev" under the server folder gives me errors.
I have installed all pre requisites.

![Screenshot Policy_Critical and alert](https://user-images.githubusercontent.com/102824897/172725632-153cb296-916f-45c2-ae9e-37c351bf3e5a.png)

**Comment by sherwyn11** [comment]
Did you ```cd``` into the server directory?

**Comment by Yager0ne** [comment]
Yes, I did cd into the server folder. I will check with the prerequisites again, just to make sure I did everything properly. Thank you so much for replying.
